### PR TITLE
Use WPILib drive bases (DifferentialDrive) for Drivetrain and TeleopDrive

### PR DESCRIPTION
**Pull request by tylertian123**
Use the [`DifferentialDrive`](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.html) class in WPILib for driving.

### CODE REVIEW

**Comment by JeremyXie123** [comment]
Code looks great, but I was wondering what the setSpeedMultiplier and setDeadZone methods did

**Comment by tylertian123** [comment]
Actually I'm leaving this branch here for now and I won't merge this until later.

**Comment by tylertian123** [comment]
> Code looks great, but I was wondering what the setSpeedMultiplier and setDeadZone methods did

@JeremyXie123 sorry about that, I was quite busy today so I didn't get to respond. Anyways, the `setSpeedMultiplier` method sets the speed multiplier for the drivetrain. Every call to `setMotors` or `DifferentialDrive.arcadeDrive` will be scaled by this before being applied to the actual motors. In this PR, it's used to implement precision drive (which currently is implemented but not bound to anything in the controls). Before this PR, it was just something that was there and never actually used.

[`DifferentialDrive.setDeadband(double)`](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.html#setDeadband(double)) sets the deadzone of the drive base:
> Sets the deadband applied to the drive inputs (e.g., joystick values).
> 
> The default value is 0.02. Inputs smaller than the deadband are set to 0.0 while inputs larger than the deadband are scaled from 0.0 to 1.0. See `applyDeadband(double, double)`.

---

Now the main advantage of the changes I've done here is that now we're handing off all the processing for converting joystick inputs into actual motor output values to the WPILib API. This makes things simpler, especially when it comes to the `TeleopDrive` command's main body. The main reason I wanted to do this is also that later on for using the limelight to align it would be convenient to be able to use the `arcadeDrive` method to split the throttle and turning (something that Marcus suggested). 

However, the main issue is that there are a lot of features we've added which involves low-level access to the motor that are harder to implement with this setup. In some places, the code was actually made more complicated, such as setting the deadband and speed multiplier for the drivetrain in `TeleopDrive`, using `ProtectedCANSparkMax` to implement overheat protection, etc. The code in our original setup was also quite similar to what the WPILib `DifferentialDrive` class does, although there is some magic that `DifferentialDrive.arcadeDrive` does that I still haven't figured out yet. Therefore, I really can't decide whether or not it's actually a good idea to merge this PR and use WPILib for the drivetrain. I'm putting this on hold for now. What do you think?

**Comment by JeremyXie123** [comment]
Given the amount of time we have to spend on things that must be coded in the robot, I believe it would be more time efficient and realistic to continue using the current setup. That's not to say, however, that learning how the differential drive works is a bad thing. If we have spare time, it may be worth looking into, as long as it doesn't completely break our code.

**Comment by tylertian123** [comment]
That's true. I'll try to understand the WPILib source code for it and see if we could apply it to our own code.

**Comment by tylertian123** [comment]
#26 replaces this PR.

**Pull request closed without merging**
